version: "3"
services:
  db:
    image: postgres:11.1-alpine
    env_file: docker/.dockerenv
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/backup:/backup

  redis:
    image: redis:4.0.11-alpine
    restart: always
    volumes:
      - ./redis/data:/data

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: docker/.dockerenv
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    links:
      - redis
      - db
    command: ["make", "app"]

  nginx:
    depends_on:
      - app
    image: nginx:1.15.7-alpine
    restart: always
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./app/:/app
